language: perl

sudo: false

perl:
   - "5.22"
   - "5.20"
   - "5.18"
   - "5.16"
   - "5.14"
   - "5.12"
   - "5.10"

install:
   - perlbrew list
   - unset PERL_CPANM_OPT
   - cpanm --mirror http://cpan.stratopan.com --quiet --notest Dist::Zilla
   - dzil authordeps | cpanm --mirror http://cpan.stratopan.com --quiet --notest
   - dzil listdeps   | cpanm --mirror http://cpan.stratopan.com --quiet --notest

script:
   - export HARNESS_OPTIONS='j:c'
   - dzil smoke --release --author
