language: perl

sudo: false

perl:
   - "5.22"
#   - "5.20"
#   - "5.18"
#   - "5.16"
#   - "5.14"
#   - "5.12"
   - "5.10"

install:
   - perlbrew list
   - TEST_PERL="$PERLBREW_PERL"
   - DZIL_PERL=`perl -e'eval"use 5.014";print $@?"5.14":$ENV{PERLBREW_PERL}'`
   - echo $DZIL_PERL
   - unset PERL_CPANM_OPT
   - perlbrew use $DZIL_PERL
   - cpanm --mirror http://cpan.stratopan.com --quiet --notest Dist::Zilla
   - dzil authordeps |tee deps| cpanm --mirror http://cpan.stratopan.com --quiet --notest
   - dzil listdeps   |tee -a deps| cpanm --mirror http://cpan.stratopan.com --quiet --notest
   - export HARNESS_OPTIONS='j:c'
   - dzil build
   - perlbrew use $TEST_PERL
   - cat deps|cpanm --mirror http://cpan.stratopan.com --quiet --notest
   - cd Pinto*
   - perl Build.PL
script:
   - AUTHOR_TESTING=1 ./Build test
