language: perl

sudo: false

perl:
   - "5.24"
   - "5.22"
   - "5.20"
   - "5.18"
   - "5.16"
   - "5.14"
   - "5.12"
   
install:
   - unset PERL_CPANM_OPT
   - cpanm --mirror http://cpan.stratopan.com --quiet --notest Dist::Zilla --skip-satisfied
   - dzil authordeps | cpanm --mirror http://cpan.stratopan.com --quiet --notest --skip-satisfied
   - dzil listdeps   | cpanm --mirror http://cpan.stratopan.com --quiet --notest --skip-satisfied

script:
   - export HARNESS_OPTIONS='j:c'
   - dzil smoke --release --author
